name: &NAME rs-ddpm-ms-classification
seed: 42
device: &DEVICE cuda
image_size: &IMAGE_SIZE 128
image_channels: &IMAGE_CHANNELS 3

label_pipeline:
  multiclass_one_h:
    - module: ffcv.transforms.ToTensor

downstream_task_specific_feature_extractor_kwargs:
  feature_section: "middle"
  feature_levels: [ 0 ]
  vectorize_output: True


# MODEL INSTANTIATION
metrics: &METRICS
  accuracy:
    module: torchmetrics.Accuracy
    kwargs:
      task: "multilabel"
      num_labels: 11
      threshold: 0.5
  recall:
    module: torchmetrics.Recall
    kwargs:
      task: "multilabel"
      num_labels: 11
      threshold: 0.5
  precision:
    module: torchmetrics.Precision
    kwargs:
      task: "multilabel"
      num_labels: 11
      threshold: 0.5

pl_module:
  module: remote_sensing_ddpm.downstream_tasks.lit_downstream_task.LitDownstreamTask
  kwargs:
    learning_rate: 0.0001
    loss:
      module: torch.nn.CrossEntropyLoss
    target_key: "multiclass_one_h"
    training_metrics: *METRICS
    validation_metrics: *METRICS
    downstream_model:
      module: remote_sensing_ddpm.downstream_tasks.downstream_task_model.DownstreamTaskModel
      kwargs:
        downstream_layer:
          module: remote_sensing_ddpm.downstream_tasks.modules.non_linear_head.NonLinearHead
          kwargs:
            input_size: 65536
            output_size: 11


# MODEL TRAINING
pl_trainer:
  accelerator: gpu
  max_epochs: 10
  log_every_n_steps: 1
  precision: "16-mixed"
  # gradient_clip_algorithm: "norm"
  enable_checkpointing: True
  # UNCOMMENT FOR DEBUGGING
  # fast_dev_run: True

pl_wandb_logger:
  project: *NAME

pl_checkpoint_callback:
  monitor: "train/CrossEntropyLoss"
  save_top_k: 3
  every_n_epochs: 5

sampling:
  shape: [*IMAGE_CHANNELS, *IMAGE_SIZE, *IMAGE_SIZE]
  strict_ckpt_loading: False
  device: *DEVICE
  batch_size: 16
