name: &NAME rs-ddpm-ms-classification
seed: 42
device: &DEVICE cuda
target_key: &TARGET_KEY "climate_zone"
num_labels: &NUM_LABELS 30
image_size: &IMAGE_SIZE 128
image_channels: &IMAGE_CHANNELS 3

label_pipeline:
  *TARGET_KEY:
    - module: remote_sensing_core.transforms.ffcv.climatezone_transform.ClimateZoneTransform
    - module: ffcv.transforms.ToTensor

downstream_task_specific_feature_extractor_kwargs:
  feature_section: "middle"
  feature_levels: [ 0 ]
  vectorize_output: True


# MODEL INSTANTIATION
metrics: &METRICS
  accuracy:
    module: torchmetrics.Accuracy
    kwargs:
      task: "multilabel"
      num_labels: *NUM_LABELS
      threshold: 0.5
  recall:
    module: torchmetrics.Recall
    kwargs:
      task: "multilabel"
      num_labels: *NUM_LABELS
      threshold: 0.5
  precision:
    module: torchmetrics.Precision
    kwargs:
      task: "multilabel"
      num_labels: *NUM_LABELS
      threshold: 0.5

pl_module:
  module: remote_sensing_ddpm.downstream_tasks.lit_downstream_task.LitDownstreamTask
  kwargs:
    learning_rate: 0.0001
    loss:
      module: torch.nn.CrossEntropyLoss
    target_key: *TARGET_KEY
    training_metrics: *METRICS
    validation_metrics: *METRICS
    downstream_model:
      module: remote_sensing_ddpm.downstream_tasks.downstream_task_model.DownstreamTaskModel
      kwargs:
        downstream_layer:
          module: remote_sensing_ddpm.downstream_tasks.modules.non_linear_head.NonLinearHead
          kwargs:
            input_size: 65536
            output_size: *NUM_LABELS


# MODEL TRAINING
pl_trainer:
  accelerator: gpu
  max_epochs: 10
  log_every_n_steps: 1
  precision: "16-mixed"
  # gradient_clip_algorithm: "norm"
  enable_checkpointing: True
  # UNCOMMENT FOR DEBUGGING
  fast_dev_run: True

pl_wandb_logger:
  project: *NAME

pl_checkpoint_callback:
  monitor: "train/CrossEntropyLoss"
  save_top_k: 3
  every_n_epochs: 5
