name: &NAME rs-ddpm-ms-segmentation
seed: 42
device: &DEVICE cuda
target_key: &TARGET_KEY "glo_30_dem"
output_dim: &OUTPUT_DIM 1
image_size: &IMAGE_SIZE 128

label_pipeline:
  *TARGET_KEY:
    - module: ffcv.fields.decoders.NDArrayDecoder
    - module: remote_sensing_core.transforms.ffcv.channel_selector.ChannelSelector
      kwargs:
        channels: 0
    - module: remote_sensing_core.transforms.ffcv.expand_dimension.ExpandDimension
      kwargs:
        axis: 1
    - module: ffcv.transforms.ToTensor

downstream_task_specific_feature_extractor_kwargs:
  feature_section: "decoder"
  feature_levels: [ 1 ]
  vectorize_output: False

# MODEL INSTANTIATION
train_metrics: &TRAIN_METRICS
  mean_squared_error:
    module: torchmetrics.MeanSquaredError
  mean_absolute_error:
    module: torchmetrics.MeanAbsoluteError

validation_metrics: &VALIDATION_METRICS
  mean_squared_error:
    module: torchmetrics.MeanSquaredError
  mean_absolute_error:
    module: torchmetrics.MeanAbsoluteError

pl_module:
  module: remote_sensing_ddpm.downstream_tasks.lit_downstream_task.LitDownstreamTask
  kwargs:
    learning_rate: 0.0001
    loss:
      module: torch.nn.MSELoss
    target_key: *TARGET_KEY
    training_metrics: *TRAIN_METRICS
    validation_metrics: *VALIDATION_METRICS
    downstream_model:
      module: remote_sensing_ddpm.downstream_tasks.downstream_task_model.DownstreamTaskModel
      kwargs:
        downstream_layer:
          module: remote_sensing_ddpm.downstream_tasks.modules.single_convolution_segmentation_head.SingleConvolutionSegmentationHead
          kwargs:
            input_size: *IMAGE_SIZE
            output_size: 120
            feature_map_channels: 128
            output_map_channels: *OUTPUT_DIM

# MODEL TRAINING
pl_trainer:
  accelerator: gpu
  max_epochs: 10
  log_every_n_steps: 1
  precision: "16-mixed"
  # gradient_clip_algorithm: "norm"
  enable_checkpointing: True
  # UNCOMMENT FOR DEBUGGING
  # fast_dev_run: True

pl_wandb_logger:
  project: *NAME

pl_checkpoint_callback:
  monitor: "train/MSELoss"
  save_top_k: 3
  every_n_epochs: 5
