name: &NAME rs-ddpm-ms-segmentation
seed: 42
device: &DEVICE cuda
target_key: &TARGET_KEY "esa_worldcover"
output_channels: &OUTPUT_CHANNELS 11
image_size: &IMAGE_SIZE 128
image_channels: &IMAGE_CHANNELS 3

label_pipeline:
  *TARGET_KEY:
    - module: ffcv.fields.decoders.NDArrayDecoder
    - module: remote_sensing_core.transforms.ffcv.esa_world_cover_transform.EsaWorldCoverTransform
      kwargs:
        divisor: 10.0
        subtractor: 1.0
    - module: remote_sensing_core.transforms.ffcv.convert.Convert
      kwargs:
        target_dtype: "int64"
    - module: ffcv.transforms.ToTensor

downstream_task_specific_feature_extractor_kwargs:
  feature_section: "decoder"
  feature_levels: [ 1 ]
  vectorize_output: False

# MODEL INSTANTIATION
metrics: &METRICS
  accuracy:
    module: remote_sensing_ddpm.utils.torchmetrics_adapter.TorchmetricsAdapter
    kwargs:
      apply_argmax: True
      device: *DEVICE
      torchmetrics_module: 
        module: torchmetrics.Accuracy
        kwargs:
          task: "multiclass"
          num_classes: *OUTPUT_CHANNELS
  mIoU:
    module: remote_sensing_ddpm.utils.torchmetrics_adapter.TorchmetricsAdapter
    kwargs:
      apply_argmax: True
      device: *DEVICE
      torchmetrics_module: 
        module: torchmetrics.JaccardIndex
        kwargs:
          task: "multiclass"
          num_classes: *OUTPUT_CHANNELS

pl_module:
  module: remote_sensing_ddpm.downstream_tasks.lit_downstream_task.LitDownstreamTask
  kwargs:
    learning_rate: 0.0001
    loss:
      module: torch.nn.CrossEntropyLoss
    target_key: *TARGET_KEY
    training_metrics: *METRICS
    validation_metrics: *METRICS
    downstream_model:
      module: remote_sensing_ddpm.downstream_tasks.downstream_task_model.DownstreamTaskModel
      kwargs:
        downstream_layer:
          module: remote_sensing_ddpm.downstream_tasks.modules.single_convolution_segmentation_head.SingleConvolutionSegmentationHead
          kwargs:
            input_size: *IMAGE_SIZE
            output_size: 120
            feature_map_channels: 128
            output_map_channels: *OUTPUT_CHANNELS

# MODEL TRAINING
pl_trainer:
  accelerator: gpu
  max_epochs: 10
  log_every_n_steps: 1
  precision: "16-mixed"
  # gradient_clip_algorithm: "norm"
  enable_checkpointing: True
  # UNCOMMENT FOR DEBUGGING
  # fast_dev_run: True

pl_wandb_logger:
  project: *NAME

pl_checkpoint_callback:
  monitor: "train/CrossEntropyLoss"
  save_top_k: 3
  every_n_epochs: 5
