name: &NAME rs-ddpm-ms-regression
seed: 42
device: &DEVICE cuda
image_size: &IMAGE_SIZE 128
image_channels: &IMAGE_CHANNELS 3

downstream_task_specific_feature_extractor_kwargs:
  feature_section: "middle"
  feature_levels: [0]
  vectorize_output: True

# MODEL INSTANTIATION
metrics: &METRICS
  mean_squared_error:
    module: torchmetrics.MeanSquaredError
  correlation:
    module: torchmetrics.SpearmanCorrCoef
    kwargs:
      num_outputs: 1

pl_module:
  module: remote_sensing_ddpm.downstream_tasks.lit_downstream_task.LitDownstreamTask
  kwargs:
    learning_rate: 0.0001
    loss:
      module: torch.nn.MSELoss
    target_key: 0
    training_metrics: *METRICS
    validation_metrics: *METRICS
    downstream_model:
      module: remote_sensing_ddpm.downstream_tasks.downstream_task_model.DownstreamTaskModel
      kwargs:
        downstream_layer:
          module: remote_sensing_ddpm.downstream_tasks.modules.non_linear_head.NonLinearHead
          kwargs:
            input_size: 65536
            output_size: 1

# MODEL TRAINING
pl_trainer:
  accelerator: gpu
  max_epochs: 10
  log_every_n_steps: 1
  precision: "16-mixed"
  # gradient_clip_algorithm: "norm"
  enable_checkpointing: True
  # UNCOMMENT FOR DEBUGGING
  # fast_dev_run: True

pl_wandb_logger:
  project: *NAME

pl_checkpoint_callback:
  monitor: "train/MSELoss"
  save_top_k: 3
  every_n_epochs: 5

sampling:
  shape: [*IMAGE_CHANNELS, *IMAGE_SIZE, *IMAGE_SIZE]
  strict_ckpt_loading: False
  device: *DEVICE
  batch_size: 16
