name: &NAME rs-ddpm-ms-classification
seed: 42
device: &DEVICE cuda
data_key: &DATA_KEY 1
image_size: &IMAGE_SIZE 128
image_channels: &IMAGE_CHANNELS 3
train_beton_file: &TRAIN_BETON_FILE /ds2/remote_sensing/ben-ge/ffcv/ben-ge-20-train.beton
validation_beton_file: &VALIDATION_BETON_FILE /ds2/remote_sensing/ben-ge/ffcv/ben-ge-20-validation.beton


sentinel_2_pipeline: &S2_PIPELINE
  - module: ffcv.fields.decoders.NDArrayDecoder
  - module: remote_sensing_core.transforms.ffcv.channel_selector.ChannelSelector
    kwargs:
      channels: [ 3, 2, 1]
  - module: remote_sensing_core.transforms.ffcv.clipping.Clipping
    kwargs:
      clip_values: [0, 10000]
  - module: remote_sensing_core.transforms.ffcv.min_max_scaler.MinMaxScaler
    kwargs:
      minimum_value: 0
      maximum_value: 10000
  - module: remote_sensing_core.transforms.ffcv.padding.Padding
    kwargs:
      padding: 4
      padding_value: 0
  - module: remote_sensing_core.transforms.ffcv.convert.Convert
    kwargs:
      target_dtype: "float32"
  - module: ffcv.transforms.ToTensor

esa_worldcover_pipeline: &EWC_PIPELINE
  - module: ffcv.fields.decoders.NDArrayDecoder
  - module: remote_sensing_core.transforms.ffcv.esa_world_cover_transform.EsaWorldCoverTransform
    kwargs:
      divisor: 10.0
      subtractor: 1.0
  - module: remote_sensing_core.transforms.ffcv.convert.Convert
    kwargs:
      target_dtype: "int64"
  - module: ffcv.transforms.ToTensor


pipelines: &PIPELINES
  climate_zone: null
  elevation_differ: null
  era_5: null
  esa_worldcover: *EWC_PIPELINE
  glo_30_dem: null
  multiclass_numer: null
  multiclass_one_h: null
  season_s1: null
  season_s2: null
  sentinel_1: null
  sentinel_2: *S2_PIPELINE
  field_names: null

# DATA SET CONFIG
train_torch_data_loader:
  module: ffcv.loader.Loader
  kwargs:
    fname: *TRAIN_BETON_FILE
    batch_size: 24
    num_workers: 4
    order:
      module: ffcv.loader.OrderOption
      args: [ 3 ] # 3 is Quasi random
    pipelines: *PIPELINES


validation_torch_data_loader:
  module: ffcv.loader.Loader
  kwargs:
    fname: *VALIDATION_BETON_FILE
    batch_size: 24
    num_workers: 4
    order:
      module: ffcv.loader.OrderOption
      args: [ 1 ]
    pipelines: *PIPELINES

# MODEL INSTANTIATION
metrics: &METRICS
  accuracy:
    module: remote_sensing_ddpm.utils.torchmetrics_adapter.TorchmetricsAdapter
    kwargs:
      apply_argmax: True
      device: *DEVICE
      torchmetrics_module: 
        module: torchmetrics.Accuracy
        kwargs:
          task: "multiclass"
          num_classes: 11
  mIoU:
    module: remote_sensing_ddpm.utils.torchmetrics_adapter.TorchmetricsAdapter
    kwargs:
      apply_argmax: True
      device: *DEVICE
      torchmetrics_module: 
        module: torchmetrics.JaccardIndex
        kwargs:
          task: "multiclass"
          num_classes: 11

pl_module:
  module: remote_sensing_ddpm.downstream_tasks.lit_downstream_task.LitDownstreamTask
  kwargs:
    learning_rate: 0.0001
    loss:
      module: torch.nn.CrossEntropyLoss
    target_key: 0
    training_metrics: *METRICS
    validation_metrics: *METRICS
    downstream_model:
      module: remote_sensing_ddpm.downstream_tasks.downstream_task_model.DownstreamTaskModel
      kwargs:
        downstream_layer:
          module: remote_sensing_ddpm.downstream_tasks.modules.single_convolution_segmentation_head.SingleConvolutionSegmentationHead
          kwargs:
            input_size: *IMAGE_SIZE
            output_size: 120
            feature_map_channels: 128
            output_map_channels: 11
        feature_extractor:
          module: remote_sensing_ddpm.downstream_tasks.modules.feature_extractor.FeatureExtractor
          kwargs:
            data_key: *DATA_KEY
            checkpoint_path: "rs-ddpm-ms/sta6sgv7/checkpoints/epoch=9-step=77640.ckpt"
            map_location: *DEVICE
            feature_section: "decoder"
            feature_levels: [1]
            vectorize_output: False
            t: 1
            p_theta_model_kwargs:
              feat_need: True
            diffusion_pl_module:
              module: lit_diffusion.ddpm.lit_ddpm.LitDDPM
              kwargs:
                diffusion_target: eps
                schedule_type: linear
                beta_schedule_steps: 1000
                beta_schedule_linear_start: 0.0001
                beta_schedule_linear_end: 0.02
                learning_rate: 0.00001
                data_key: *DATA_KEY
                learning_rate_scheduler_config:
                  module: torch.optim.lr_scheduler.LinearLR
                  delay: 1
                p_theta_model:
                  module: remote_sensing_ddpm.p_theta_models.ddpm_cd_model.sr3_modules.unet.UNet
                  kwargs:
                    in_channel: *IMAGE_CHANNELS
                    out_channel: *IMAGE_CHANNELS
                    norm_groups: 32
                    inner_channel: 128
                    channel_mults: [ 1, 2, 4, 8, 8 ]
                    attn_res: [ 16 ]
                    res_blocks: 2
                    dropout: 0.2
                    image_size: *IMAGE_SIZE

# MODEL TRAINING
pl_trainer:
  accelerator: gpu
  max_epochs: 10
  log_every_n_steps: 1
  precision: "16-mixed"
  # gradient_clip_algorithm: "norm"
  enable_checkpointing: True
  # UNCOMMENT FOR DEBUGGING
  # fast_dev_run: True

pl_wandb_logger:
  project: *NAME

pl_checkpoint_callback:
  monitor: "train/CrossEntropyLoss"
  save_top_k: 3
  every_n_epochs: 5

sampling:
  shape: [*IMAGE_CHANNELS, *IMAGE_SIZE, *IMAGE_SIZE]
  strict_ckpt_loading: False
  device: *DEVICE
  batch_size: 16
