device: &DEVICE cuda
image_key: &IMAGE_KEY "image"
label_key: &LABEL_KEY "label"
image_size: &IMAGE_SIZE 128
image_channels: &IMAGE_CHANNELS 6


# DATA SET CONFIG
train_torch_data_loader:
  module: torch.utils.data.DataLoader
  kwargs:
    batch_size: 24
    num_workers: 4
    shuffle: True
    dataset:
      module: remote_sensing_ddpm.datasets.dfc_2020.dfc_2020.DFC2020
      kwargs:
        path: "/ds2/remote_sensing/grss-dfc-20"
        subset: test
        s2_bands: [ 3, 2, 1, 7]
        use_s1: True
        no_snow_and_savanna: True
        label_mode: "classification"
        label_dtype: "float"
        s1_augmentations:
          module: remote_sensing_ddpm.datasets.dfc_2020.augmentations.min_max_scaler.TorchMinMaxScaler
          kwargs:
            minimum_value: 0
            maximum_value: 1
            interval_min: -1.0
            interval_max: 1.0
        s2_augmentations:
          module: remote_sensing_ddpm.datasets.dfc_2020.augmentations.min_max_scaler.TorchMinMaxScaler
          kwargs:
            minimum_value: 0
            maximum_value: 1
            interval_min: -1.0
            interval_max: 1.0
        batch_augmentation:
          module: torch.nn.Sequential
          args:
            - module: remote_sensing_ddpm.datasets.dfc_2020.augmentations.transform_image_and_label.TransformImageAndLabel
              kwargs:
                image_key: *IMAGE_KEY
                label_key: *LABEL_KEY
                transform_op:
                  module: torchvision.transforms.RandomCrop
                  kwargs:
                    size: 120
            - module: remote_sensing_ddpm.datasets.dfc_2020.augmentations.transform_image_and_label.TransformImageAndLabel
              kwargs:
                image_key: *IMAGE_KEY
                label_key: *LABEL_KEY
                only_image: True
                transform_op:
                  module: torchvision.transforms.Pad
                  kwargs:
                    padding: 4

validation_torch_data_loader:
  module: torch.utils.data.DataLoader
  kwargs:
    batch_size: 24
    num_workers: 4
    shuffle: False
    dataset:
      module: remote_sensing_ddpm.datasets.dfc_2020.dfc_2020.DFC2020
      kwargs:
        path: "/ds2/remote_sensing/grss-dfc-20"
        subset: val
        s2_bands: [ 3, 2, 1, 7 ]
        no_snow_and_savanna: True
        use_s1: True
        label_mode: "classification"
        label_dtype: "float"
        s1_augmentations:
          module: remote_sensing_ddpm.datasets.dfc_2020.augmentations.min_max_scaler.TorchMinMaxScaler
          kwargs:
            minimum_value: 0
            maximum_value: 1
            interval_min: -1.0
            interval_max: 1.0
        s2_augmentations:
          module: remote_sensing_ddpm.datasets.dfc_2020.augmentations.min_max_scaler.TorchMinMaxScaler
          kwargs:
            minimum_value: 0
            maximum_value: 1
            interval_min: -1.0
            interval_max: 1.0
        batch_augmentation:
          module: torch.nn.Sequential
          args:
            - module: remote_sensing_ddpm.datasets.dfc_2020.augmentations.transform_image_and_label.TransformImageAndLabel
              kwargs:
                image_key: *IMAGE_KEY
                label_key: *LABEL_KEY
                transform_op:
                  module: torchvision.transforms.RandomCrop
                  kwargs:
                    size: 120
            - module: remote_sensing_ddpm.datasets.dfc_2020.augmentations.transform_image_and_label.TransformImageAndLabel
              kwargs:
                image_key: *IMAGE_KEY
                label_key: *LABEL_KEY
                only_image: True
                transform_op:
                  module: torchvision.transforms.Pad
                  kwargs:
                    padding: 4


# FEATURE EXTRACTOR CONFIG
feature_extractor:
  module: remote_sensing_ddpm.downstream_tasks.modules.feature_extractor.FeatureExtractor
  kwargs:
    data_key: *IMAGE_KEY
    checkpoint_path: "/netscratch2/alontke/master_thesis/code/ssl-ddpm-rs/rs-ddpm-ms/isam22bx/checkpoints/epoch=19-step=155280.ckpt"
    map_location: *DEVICE
    t: 1
    p_theta_model_kwargs:
      feat_need: True
    diffusion_pl_module:
      module: lit_diffusion.ddpm.lit_ddpm.LitDDPM
      kwargs:
        diffusion_target: eps
        schedule_type: linear
        beta_schedule_steps: 1000
        beta_schedule_linear_start: 0.0001
        beta_schedule_linear_end: 0.02
        learning_rate: 0.00001
        data_key: *IMAGE_KEY
        learning_rate_scheduler_config:
          module: torch.optim.lr_scheduler.LinearLR
          delay: 1
        p_theta_model:
          module: remote_sensing_ddpm.p_theta_models.ddpm_cd_model.sr3_modules.unet.UNet
          kwargs:
            in_channel: *IMAGE_CHANNELS
            out_channel: *IMAGE_CHANNELS
            norm_groups: 32
            inner_channel: 128
            channel_mults: [ 1, 2, 4, 8, 8 ]
            attn_res: [ 16 ]
            res_blocks: 2
            dropout: 0.2
            image_size: *IMAGE_SIZE