name: &NAME rs-ddpm-ms
seed: 42

# DATA SET CONFIG
train_torch_data_loader:
  module: torch.utils.data.DataLoader
  kwargs:
    batch_size: 24
    shuffle: True
    num_workers: 4
    dataset:
      module: remote_sensing_core.ben_ge.ben_ge_dataset.BenGe
      kwargs:
        data_index_path: /netscratch2/nkesseli/master-thesis-benge/src/_master_thesis_benge_supervised_learning/scripts/data-split/data-split-folder/ben-ge-train20.csv
        sentinel_1_2_metadata_path: /ds2/remote_sensing/ben-ge/ben-ge/ben-ge_meta.csv
        sentinel_1_modality:
          module: remote_sensing_core.ben_ge.modalities.sentinel_1.Sentinel1Modality
          kwargs:
            data_root_path: /ds2/remote_sensing/ben-ge/ben-ge/sentinel-1/
            numpy_dtype: "float32"
        sentinel_2_modality:
          module: remote_sensing_core.ben_ge.modalities.sentinel_2.Sentinel2Modality
          kwargs:
            data_root_path: /ds2/remote_sensing/ben-ge/ben-ge/sentinel-2/
            numpy_dtype: "float32"
            s2_bands: "RGB"
            transform:
              module: remote_sensing_core.ben_ge.modalities.sentinel_2.Sentinel2Transform
              kwargs:
                clip_values: [ 0, 10000 ]
                transform:
                  module: lit_diffusion.utils.min_max_scaler.MinMaxScaler
                  kwargs:
                    minimum_value: 0
                    maximum_value: 10000
        esa_world_cover_modality:
          module: remote_sensing_core.ben_ge.modalities.esa_worldcover.EsaWorldCoverModality
          kwargs:
            data_root_path: /ds2/remote_sensing/ben-ge/ben-ge/esaworldcover/npy/
            numpy_dtype: "float32"
            esa_world_cover_index_path: /netscratch2/nkesseli/master-thesis-benge/src/_master_thesis_benge_supervised_learning/scripts/data-split/data-split-folder/ben-ge-train20.csv
            multiclass_label_top_k: 1
        glo_30_dem_modality:
          module: remote_sensing_core.ben_ge.modalities.glo_30_dem.Glo30DemModality
          kwargs:
            data_root_path: /ds2/remote_sensing/ben-ge/ben-ge/glo-30_dem/
            numpy_dtype: "float32"
        transform:
          module: remote_sensing_core.transforms.composite_image_transform.CompositeImageTransform
          kwargs:
            convert_from_numpy: True
            padding_parameters:
              padding: 4

validation_torch_data_loader:
  module: torch.utils.data.DataLoader
  kwargs:
    batch_size: 24
    shuffle: False
    num_workers: 4
    dataset:
      module: remote_sensing_core.ben_ge.ben_ge_dataset.BenGe
      kwargs:
        data_index_path: /netscratch2/nkesseli/master-thesis-benge/src/_master_thesis_benge_supervised_learning/scripts/data-split/data-split-folder/ben-ge-test20.csv
        sentinel_1_2_metadata_path: /ds2/remote_sensing/ben-ge/ben-ge/ben-ge_meta.csv
        sentinel_1_modality:
          module: remote_sensing_core.ben_ge.modalities.sentinel_1.Sentinel1Modality
          kwargs:
            data_root_path: /ds2/remote_sensing/ben-ge/ben-ge/sentinel-1/
            numpy_dtype: "float32"
        sentinel_2_modality:
          module: remote_sensing_core.ben_ge.modalities.sentinel_2.Sentinel2Modality
          kwargs:
            data_root_path: /ds2/remote_sensing/ben-ge/ben-ge/sentinel-2/
            numpy_dtype: "float32"
            s2_bands: "RGB"
            transform:
              module: remote_sensing_core.ben_ge.modalities.sentinel_2.Sentinel2Transform
              kwargs:
                clip_values: 10000
                transform:
                  module: lit_diffusion.utils.min_max_scaler.MinMaxScaler
                  kwargs:
                    minimum_value: 0
                    maximum_value: 10000
        esa_world_cover_modality:
          module: remote_sensing_core.ben_ge.modalities.esa_worldcover.EsaWorldCoverModality
          kwargs:
            data_root_path: /ds2/remote_sensing/ben-ge/ben-ge/esaworldcover/npy/
            numpy_dtype: "float32"
            esa_world_cover_index_path: /netscratch2/nkesseli/master-thesis-benge/src/_master_thesis_benge_supervised_learning/scripts/data-split/data-split-folder/ben-ge-test20.csv
            multiclass_label_top_k: 1
        glo_30_dem_modality:
          module: remote_sensing_core.ben_ge.modalities.glo_30_dem.Glo30DemModality
          kwargs:
            data_root_path: /ds2/remote_sensing/ben-ge/ben-ge/glo-30_dem/
            numpy_dtype: "float32"
        transform:
          module: remote_sensing_core.transforms.composite_image_transform.CompositeImageTransform
          kwargs:
            convert_from_numpy: True
            padding_parameters:
              padding: 4


# MODEL INSTANTIATION
pl_module:
  module: remote_sensing_ddpm.downstream_tasks.lit_downstream_task.LitDownstreamTask
  kwargs:
    learning_rate: 0.0001
    loss:
      module: torch.nn.BCELoss
    target_key: "multiclass_label"
    training_metrics:
      Accuracy: torchmetrics.Accuracy
      kwargs:
        task: "multiclass"
        num_classes: 11
    validation_metrics:
      Accuracy: torchmetrics.Accuracy
      kwargs:
        task: "multiclass"
        num_classes: 11
    downstream_model:
      module: remote_sensing_ddpm.downstream_tasks.downstream_models.vector_output.VectorOutputDownstreamTask
      kwargs:
        input_size: 65536
        output_size: 11
        feature_extractor:
          module: remote_sensing_ddpm.downstream_tasks.downstream_models.modules.feature_extractor.FeatureExtractor
          kwargs:
            data_key: "sentinel_2"
            checkpoint_path: "rs-ddpm-ms/6dpqsyxu/checkpoints/epoch=9-step=5000.ckpt"
            map_location: "cuda"
            feature_section: "middle"
            feature_levels: [0]
            vectorize_output: True
            t: 0
            p_theta_model_kwargs:
              feat_need: True
            diffusion_pl_module:
              module: lit_diffusion.ddpm.lit_ddpm.LitDDPM
              kwargs:
                diffusion_target: eps
                schedule_type: linear
                beta_schedule_steps: 1000
                beta_schedule_linear_start: 0.0001
                beta_schedule_linear_end: 0.02
                learning_rate: 0.00001
                data_key: "sentinel_2"
                learning_rate_scheduler_config:
                  module: torch.optim.lr_scheduler.LinearLR
                  delay: 1
                p_theta_model:
                  module: remote_sensing_ddpm.p_theta_models.ddpm_cd_model.sr3_modules.unet.UNet
                  kwargs:
                    in_channel: 3
                    out_channel: 3
                    norm_groups: 32
                    inner_channel: 128
                    channel_mults: [ 1, 2, 4, 8, 8 ]
                    attn_res: [ 16 ]
                    res_blocks: 2
                    dropout: 0.2
                    image_size: 128

# MODEL TRAINING
pl_trainer:
  accelerator: gpu
  max_epochs: 100
  log_every_n_steps: 1
  precision: "16-mixed"
  # gradient_clip_algorithm: "norm"
  enable_checkpointing: True
  # UNCOMMENT FOR DEBUGGING
  fast_dev_run: True

pl_wandb_logger:
  project: *NAME

pl_checkpoint_callback:
  monitor: "train/BCELoss"
  save_top_k: 3
  every_n_epochs: 5

sampling:
  shape: [3, 128, 128]
  strict_ckpt_loading: False
  device: cuda
  batch_size: 16
