device: &DEVICE cuda
data_key: &DATA_KEY "sentinel_2"
sentinel_1_key: &S1_KEY "sentinel_1"
image_size: &IMAGE_SIZE 128
image_channels: &IMAGE_CHANNELS 6


# DATA SET CONFIG
tuple_mapping: &TUPLE_MAPPING [*S1_KEY, *DATA_KEY]
train_torch_data_loader:
  module: remote_sensing_ddpm.utils.ffcv_loader_wrapper.FFCVLoaderWrapper
  kwargs:
    fname: *TRAIN_BETON_FILE
    batch_size: 24
    num_workers: 4
    order:
      module: ffcv.loader.OrderOption
      args: [ 3 ] # 3 is Quasi random
    pipelines: *PIPELINES
    mapping: *TUPLE_MAPPING


validation_torch_data_loader:
  module: remote_sensing_ddpm.utils.ffcv_loader_wrapper.FFCVLoaderWrapper
  kwargs:
    fname: *VALIDATION_BETON_FILE
    batch_size: 24
    num_workers: 4
    order:
      module: ffcv.loader.OrderOption
      args: [ 1 ]
    pipelines: *PIPELINES
    mapping: *TUPLE_MAPPING


# FEATURE EXTRACTOR CONFIG
feature_extractor:
  module: remote_sensing_ddpm.downstream_tasks.modules.feature_extractor.FeatureExtractor
  kwargs:
    data_key: *DATA_KEY
    checkpoint_path: "/netscratch2/alontke/master_thesis/code/ssl-ddpm-rs/rs-ddpm-ms/isam22bx/checkpoints/epoch=19-step=155280.ckpt"
    map_location: *DEVICE
    t: 1
    p_theta_model_kwargs:
      feat_need: True
    diffusion_pl_module:
      module: lit_diffusion.ddpm.lit_ddpm.LitDDPM
      kwargs:
        diffusion_target: eps
        schedule_type: linear
        beta_schedule_steps: 1000
        beta_schedule_linear_start: 0.0001
        beta_schedule_linear_end: 0.02
        learning_rate: 0.00001
        stack_inputs_keys:
          - *S1_KEY
        auxiliary_p_theta_model_input:
          sentinel_1: *S1_KEY
        data_key: *DATA_KEY
        learning_rate_scheduler_config:
          module: torch.optim.lr_scheduler.LinearLR
          delay: 1
        p_theta_model:
          module: remote_sensing_ddpm.p_theta_models.ddpm_cd_model.sr3_modules.unet.UNet
          kwargs:
            in_channel: *IMAGE_CHANNELS
            out_channel: *IMAGE_CHANNELS
            norm_groups: 32
            inner_channel: 128
            channel_mults: [ 1, 2, 4, 8, 8 ]
            attn_res: [ 16 ]
            res_blocks: 2
            dropout: 0.2
            image_size: *IMAGE_SIZE